### ISSUE TITLE
Publish crate to crates.io

### ISSUE THREAD

**Issue by Chenjox** [acdenisSK/serenity_commands#1]
Hello,

my friend and I currently write a bot in rust and are amazed with your crate, as it creates a very good `code to macro` ratio. It is a style that appeals to us, so to speak.

We'd like to import it into out project, but we only want to pull crates from crates.io only.

Would it be viable to publish (maybe in a very WIP version) to crates.io? Or give us a current timeframe when planning to do so? We're not in a hurry, but there are more enjoyable tasks to do, than to hook up commands in serenitys system.

**Comment by acdenisSK** [comment]
Hi.
> [we] are amazed with your crate, as it creates a very good code to macro ratio. It is a style that appeals to us, so to speak.

That is great to hear. The library is to aid with registering and parsing application commands. It generates code you would have likely written yourself anyway.

> Would it be viable to publish (maybe in a very WIP version) to crates.io?

Unfortunately, no. I do not plan on publishing it to https://crates.io until it is either finished, or in a good shape for external use (that is, people can easily and readily pull in and use the library without much hassle or bugs). Besides, it is not possible to do so in the current state, because [it depends on Serenity from its `current` Git branch](https://github.com/acdenisSK/serenity_commands/blob/master/serenity_commands/Cargo.toml#L11-L15). You are only allowed to publish crates whose dependencies are also on https://crates.io.

> we only want to pull crates from crates.io only.

Any specific reason? Perhaps the interface changing unexpectedly because you invoked `cargo update`? If it is that, you can pin to a specific commit and not worry. For example, to pin to the latest commit (as of this writing):
```toml
[dependencies.serenity_commands]
git = "https://github.com/acdenisSK/serenity_commands"
rev = "a5a9c2388dfdf9bc212d8a07afd03395fb9aee7d"
```

> Or give us a current timeframe when planning to do so? 

Giving specific timeframes is not wise sometimes, but this library won't do a lot. Probably by the end of December, or the beginning of January is when I'll make the first release. I'd like to tie it to the v0.10.10 Serenity release.

**Comment by Chenjox** [comment]
> Any specific reason? Perhaps the interface changing unexpectedly because you invoked cargo update? If it is that, you can pin to a specific commit and not worry. For example, to pin to the latest commit (as of this writing):

We weren't aware of this cargo feature. I think this will help for now. Thank you for that tip!

> Giving specific timeframes is not wise sometimes, but this library won't do a lot. Probably by the end of December, or the beginning of January is when I'll make the first release. I'd like to tie it to the v0.10.10 Serenity release.

We can wait, we can do other stuff in the meantime. Thank you for your great macros!
